spring:
  profiles:
    active: mysql
        
---
spring:
  datasource:
    hikari:
      username: coding
      password: life
      jdbc-url: jdbc:mysql://localhost:3306/wonderful?useUnicode=true&characterEncoding=utf8&serverTiemzone=Asia/Seoul
      driver-class-name: com.mysql.cj.jdbc.Driver
  config:
    activate:
      on-profile: mysql
      
---
spring:
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password:
      driver-class-name: org.h2.Driver
  config:
    activate:
      on-profile: local